server:
  shutdown: graceful
  port: 8090

spring:
  jpa:
    open-in-view: true
    hibernate.ddl-auto: update
#    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

custom:
  service:
    url: http://localhost:8090
    memorySizeMB: 2
  task-executor:
    core-size: 6
    max-size: 10
    queue-capacity: 10
    thread-prefix: custom-executor